-- Legacy file kept for historical reference only.
--
-- Mission Control schema initialization now uses Alembic migrations:
--   mission_control_api/alembic/versions/
--
-- Current default flow:
-- 1) mission-control-api container starts
-- 2) runs `alembic upgrade head`
-- 3) starts API service
--
-- Do not add new schema changes in this file.
